// Antenna design (preprocessor) feature module
export * from './DesignPage'
export { default as Scene3D } from './Scene3D'
export { default as WireGeometry } from './WireGeometry'
export { default as DesignCanvas } from './DesignCanvas'
export { default as TreeViewPanel } from './TreeViewPanel'
export { default as PropertiesPanel } from './PropertiesPanel'
export { default as RibbonMenu } from './RibbonMenu'
export { default as ViewControls } from './ViewControls'
export { default as ResultsPanel } from './ResultsPanel'
export { default as ColorScaleLegend } from './ColorScaleLegend'
export { default as RadiationPatternPanel } from './RadiationPatternPanel'
export { default as PolarPlot2D } from './PolarPlot2D'
export { default as Pattern3D } from './Pattern3D'
// Dialog components (Task 12)
export * from './DipoleDialog'
export * from './LoopDialog'
export * from './HelixDialog'
export * from './RodDialog'
export * from './LumpedElementDialog'

