/**
 * Compute preview geometry for antenna dialogs.
 * These are lightweight client-side approximations for live 3D preview.
 * The actual mesh is always generated by the backend.
 */

import type { PreviewNode, PreviewEdge } from '@/components/WirePreview3D';

// ---------------------------------------------------------------------------
// Dipole preview
// ---------------------------------------------------------------------------

export interface DipolePreviewParams {
  length: number;
  radius: number;
  gap: number;
  segments: number;
  position: { x: number; y: number; z: number };
  orientation: { x: number; y: number; z: number };
}

export function computeDipolePreview(
  params: DipolePreviewParams,
): { nodes: PreviewNode[]; edges: PreviewEdge[] } {
  const { length, gap, segments, position, orientation } = params;
  if (length <= 0 || segments < 1) return { nodes: [], edges: [] };

  // Normalize orientation
  const mag = Math.sqrt(
    orientation.x ** 2 + orientation.y ** 2 + orientation.z ** 2,
  );
  const dir = mag > 1e-12
    ? { x: orientation.x / mag, y: orientation.y / mag, z: orientation.z / mag }
    : { x: 0, y: 0, z: 1 };

  const halfLen = length / 2;
  const halfGap = gap / 2;
  const segCount = Math.max(Math.round(segments), 2);
  const armSegments = Math.max(Math.floor(segCount / 2), 1);

  const nodes: PreviewNode[] = [];
  const edges: PreviewEdge[] = [];
  let nodeId = 1;

  // Lower arm: from -halfLen to -halfGap
  for (let i = 0; i <= armSegments; i++) {
    const t = -halfLen + (halfLen - halfGap) * (i / armSegments);
    nodes.push({
      id: nodeId++,
      x: position.x + t * dir.x,
      y: position.y + t * dir.y,
      z: position.z + t * dir.z,
      radius: params.radius,
    });
  }

  // Upper arm: from +halfGap to +halfLen
  for (let i = 0; i <= armSegments; i++) {
    const t = halfGap + (halfLen - halfGap) * (i / armSegments);
    nodes.push({
      id: nodeId++,
      x: position.x + t * dir.x,
      y: position.y + t * dir.y,
      z: position.z + t * dir.z,
      radius: params.radius,
    });
  }

  // Edges within lower arm
  for (let i = 1; i <= armSegments; i++) {
    edges.push({ node_start: i, node_end: i + 1 });
  }

  // Edges within upper arm
  const upperStart = armSegments + 2;
  for (let i = 0; i < armSegments; i++) {
    edges.push({ node_start: upperStart + i, node_end: upperStart + i + 1 });
  }

  return { nodes, edges };
}

// ---------------------------------------------------------------------------
// Loop preview
// ---------------------------------------------------------------------------

export interface LoopPreviewParams {
  radius: number;
  wireRadius: number;
  segments: number;
  position: { x: number; y: number; z: number };
  orientation: { rotX: number; rotY: number; rotZ: number };
}

function rotatePoint(
  x: number, y: number, z: number,
  rx: number, ry: number, rz: number,
): [number, number, number] {
  // Apply Euler rotation ZYX order (degrees → radians)
  const toRad = Math.PI / 180;
  const ax = rx * toRad;
  const ay = ry * toRad;
  const az = rz * toRad;

  // Rotation around X
  const y1 = y * Math.cos(ax) - z * Math.sin(ax);
  const z1 = y * Math.sin(ax) + z * Math.cos(ax);
  const x1 = x;

  // Rotation around Y
  const x2 = x1 * Math.cos(ay) + z1 * Math.sin(ay);
  const z2 = -x1 * Math.sin(ay) + z1 * Math.cos(ay);
  const y2 = y1;

  // Rotation around Z
  const x3 = x2 * Math.cos(az) - y2 * Math.sin(az);
  const y3 = x2 * Math.sin(az) + y2 * Math.cos(az);
  const z3 = z2;

  return [x3, y3, z3];
}

export function computeLoopPreview(
  params: LoopPreviewParams,
): { nodes: PreviewNode[]; edges: PreviewEdge[] } {
  const { radius, wireRadius, segments, position, orientation } = params;
  if (radius <= 0 || segments < 3) return { nodes: [], edges: [] };

  const segCount = Math.max(Math.round(segments), 3);
  const nodes: PreviewNode[] = [];
  const edges: PreviewEdge[] = [];

  // Circle in XY plane, then rotate
  for (let i = 0; i < segCount; i++) {
    const angle = (2 * Math.PI * i) / segCount;
    const lx = radius * Math.cos(angle);
    const ly = radius * Math.sin(angle);
    const lz = 0;

    const [rx, ry, rz] = rotatePoint(
      lx, ly, lz,
      orientation.rotX, orientation.rotY, orientation.rotZ,
    );

    nodes.push({
      id: i + 1,
      x: position.x + rx,
      y: position.y + ry,
      z: position.z + rz,
      radius: wireRadius,
    });
  }

  // Close the loop
  for (let i = 0; i < segCount; i++) {
    edges.push({
      node_start: i + 1,
      node_end: (i + 1) % segCount + 1,
    });
  }

  return { nodes, edges };
}

// ---------------------------------------------------------------------------
// Rod preview
// ---------------------------------------------------------------------------

export interface RodPreviewParams {
  start_x: number;
  start_y: number;
  start_z: number;
  end_x: number;
  end_y: number;
  end_z: number;
  radius: number;
  segments: number;
}

export function computeRodPreview(
  params: RodPreviewParams,
): { nodes: PreviewNode[]; edges: PreviewEdge[] } {
  const { start_x, start_y, start_z, end_x, end_y, end_z, radius, segments } = params;
  const segCount = Math.max(Math.round(segments), 1);

  const dist = Math.sqrt(
    (end_x - start_x) ** 2 + (end_y - start_y) ** 2 + (end_z - start_z) ** 2,
  );
  if (dist < 1e-12) return { nodes: [], edges: [] };

  const nodes: PreviewNode[] = [];
  const edges: PreviewEdge[] = [];

  for (let i = 0; i <= segCount; i++) {
    const t = i / segCount;
    nodes.push({
      id: i + 1,
      x: start_x + t * (end_x - start_x),
      y: start_y + t * (end_y - start_y),
      z: start_z + t * (end_z - start_z),
      radius,
    });
  }

  for (let i = 0; i < segCount; i++) {
    edges.push({ node_start: i + 1, node_end: i + 2 });
  }

  return { nodes, edges };
}
