"""Unit tests for Phase 8 Step 6 — Projects service hardening.

Covers:
- Schema validation constraints (description, project_id bounds)
- IMAGE_KEY_PATTERN extension whitelist
- Folder cycle detection helper
"""

import pytest
from pydantic import ValidationError

from backend.projects.documentation_service import DocumentationService
from backend.projects.schemas import (
    ProjectBase,
    ProjectUpdate,
    SubmissionCreate,
)

# ══════════════════════════════════════════════════════════════════════════════
#  Schema Validation
# ══════════════════════════════════════════════════════════════════════════════


class TestProjectSchemaConstraints:
    """Verify max_length on description fields."""

    def test_description_within_limit(self):
        p = ProjectBase(name="Test", description="A" * 5000)
        assert len(p.description) == 5000

    def test_description_exceeds_limit(self):
        with pytest.raises(ValidationError, match="description"):
            ProjectBase(name="Test", description="A" * 5001)

    def test_description_none_allowed(self):
        p = ProjectBase(name="Test", description=None)
        assert p.description is None

    def test_update_description_within_limit(self):
        u = ProjectUpdate(description="B" * 5000)
        assert len(u.description) == 5000

    def test_update_description_exceeds_limit(self):
        with pytest.raises(ValidationError, match="description"):
            ProjectUpdate(description="B" * 5001)


class TestSubmissionSchemaConstraints:
    """Verify bounds on SubmissionCreate.project_id."""

    def test_project_id_valid(self):
        s = SubmissionCreate(project_id="abc-123")
        assert s.project_id == "abc-123"

    def test_project_id_empty_rejected(self):
        with pytest.raises(ValidationError):
            SubmissionCreate(project_id="")

    def test_project_id_too_long_rejected(self):
        with pytest.raises(ValidationError):
            SubmissionCreate(project_id="x" * 101)

    def test_project_id_at_max_length(self):
        s = SubmissionCreate(project_id="x" * 100)
        assert len(s.project_id) == 100


# ══════════════════════════════════════════════════════════════════════════════
#  IMAGE_KEY_PATTERN — extension whitelist
# ══════════════════════════════════════════════════════════════════════════════


class TestImageKeyPattern:
    """validate_image_key should accept only known image extensions."""

    @pytest.mark.parametrize(
        "key",
        [
            "img_aabbccddeeff.png",
            "img_aabbccddeeff.jpg",
            "img_aabbccddeeff.jpeg",
            "img_aabbccddeeff.gif",
            "img_aabbccddeeff.svg",
            "img_aabbccddeeff.webp",
        ],
    )
    def test_valid_image_keys(self, key):
        DocumentationService.validate_image_key(key)  # should not raise

    @pytest.mark.parametrize(
        "key",
        [
            "img_aabbccddeeff.exe",
            "img_aabbccddeeff.html",
            "img_aabbccddeeff.php",
            "img_aabbccddeeff.js",
            "img_aabbccddeeff.PDF",  # uppercase not generated by service
            "../../../etc/passwd",
            "img_short.png",  # hex too short
        ],
    )
    def test_invalid_image_keys(self, key):
        with pytest.raises(ValueError, match="Invalid image key"):
            DocumentationService.validate_image_key(key)


# ══════════════════════════════════════════════════════════════════════════════
#  Folder Cycle Detection
# ══════════════════════════════════════════════════════════════════════════════


class TestFolderCycleDetection:
    """Test _check_folder_cycle helper from folder_routes."""

    @pytest.mark.asyncio
    async def test_no_cycle_root_parent(self):
        """Moving under a root-level folder should succeed."""
        from unittest.mock import AsyncMock

        from backend.projects.folder_routes import _check_folder_cycle

        folder_repo = AsyncMock()
        # parent "B" has no parent (root level)
        folder_repo.get_folder.return_value = {"id": "B", "parent_folder_id": None}

        # Should not raise
        await _check_folder_cycle("A", "B", folder_repo)

    @pytest.mark.asyncio
    async def test_direct_cycle_detected(self):
        """A → B where B's parent is A should raise."""
        from unittest.mock import AsyncMock

        from fastapi import HTTPException

        from backend.projects.folder_routes import _check_folder_cycle

        folder_repo = AsyncMock()
        # B's parent is A — so moving A under B creates A→B→A
        folder_repo.get_folder.return_value = {"id": "B", "parent_folder_id": "A"}

        with pytest.raises(HTTPException) as exc_info:
            await _check_folder_cycle("A", "B", folder_repo)
        assert exc_info.value.status_code == 400
        assert "cycle" in exc_info.value.detail.lower()

    @pytest.mark.asyncio
    async def test_deep_cycle_detected(self):
        """A → B → C where we try to move A under C — detects A in chain."""
        from unittest.mock import AsyncMock

        from fastapi import HTTPException

        from backend.projects.folder_routes import _check_folder_cycle

        folder_repo = AsyncMock()
        # C → B → A chain
        folder_repo.get_folder.side_effect = [
            {"id": "C", "parent_folder_id": "B"},  # C's parent is B
            {"id": "B", "parent_folder_id": "A"},  # B's parent is A → cycle!
        ]

        with pytest.raises(HTTPException) as exc_info:
            await _check_folder_cycle("A", "C", folder_repo)
        assert exc_info.value.status_code == 400

    @pytest.mark.asyncio
    async def test_no_cycle_independent(self):
        """Moving A under D where D→E (no A) should succeed."""
        from unittest.mock import AsyncMock

        from backend.projects.folder_routes import _check_folder_cycle

        folder_repo = AsyncMock()
        folder_repo.get_folder.side_effect = [
            {"id": "D", "parent_folder_id": "E"},
            {"id": "E", "parent_folder_id": None},  # root
        ]

        await _check_folder_cycle("A", "D", folder_repo)  # no raise
